name: tomo2plt
channels:
  - defaults
dependencies:
  - python=3.9
  - pip>=19.3
  - pip:
    - numpy>=1.23
    - scipy==1.9.1
    - matplotlib>=3.6
    - pandas>=1.5
    - imageio
    - pyyaml
    - pyshp
    - tqdm
